<?php
/**
 * @var $block \Lof\ProductTags\Block\Tag\Product\ListProduct
 */
?>
<?php
$tags = $this->getTagCollection();
$title = $this->getTagHelper()->getGeneralConfig("tag_sidebar_title");
if($tags && $tags->getSize()){
	?>
	<div class="block block-tags block-product-tags">
		<div class="block-title"><h2><?php echo $title; ?></h2></div>
		<div class="block-content">
			<ul style="padding: 0px;" class="list-tags">
				<?php foreach($tags as $tag): ?>
				<li style="list-style-type: none; float: left; margin:5px 10px; border: 1px solid #000000; border-radius: 5px; padding: 5px;"><a href="<?php
				echo $this->getTagHelper()->getTagUrl($tag->getIdentifier()); ?>">
				<style>
                    li:hover{
                        background-color: #e4e4e4;
                    }
                    a:hover{
                        color: black;
                        text-decoration: none;
                    }
                </style>
                <?php 
					echo $tag->getTagTitle(); 
				?>
                </a>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
	<?php
}
?>